apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-nodeport
spec:
  type: NodePort
  selector:
    app: myapp-jenkins
  ports:
   - name: jenkins-port
     protocol: TCP
     port: 8000
     targetPort: 8080
     nodePort: 30004
   - name: jenkins-host-port
     protocol: TCP
     port: 50002
     targetPort: 50000
     nodePort: 30005
 #pushing into git
         
