apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: myapp-tomcat
  ports:
   - name: tomcat-port
     protocol: TCP
     port: 7000
     targetPort: 8080
   - name: tomcat-host-port
     protocol: TCP
     port: 50001
     targetPort: 50000

         
