apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-nodeport
spec:
  type: NodePort
  selector:
    app: myapp-tomcat
  ports:
   - name: tomcat-port
     protocol: TCP
     port: 7000
     targetPort: 8080
     nodePort: 30001
   - name: tomcat-host-port
     protocol: TCP
     port: 50001
     targetPort: 50000
     nodePort: 30002

         
